name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell *

  check-single-header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Generate single header
        run: ./make_single_header.py -o generated_single_header.hpp

      - name: Compare against committed header
        run: diff cvl_single_header.hpp generated_single_header.hpp

  build-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            gcc-16 \
            g++-16

      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Build examples
        run: |
          cmake -B "$GITHUB_WORKSPACE/build" -S "$GITHUB_WORKSPACE" -G Ninja \
            -DCMAKE_C_COMPILER=gcc-16 \
            -DCMAKE_CXX_COMPILER=g++-16
          cmake --build "$GITHUB_WORKSPACE/build" --target examples
